### ISSUE TITLE
Throws up error when clicked beyond the Chrome Rate limits

### ISSUE THREAD

**Issue by Pacific-Alliance-Dev** [Sumedhn97/DragonCapture#1]
When Capture Button is clicked too many times in a short span, this error is seen:

Unchecked runtime.lastError: This request exceeds the MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND quota.

**Comment by Sumedhn97** [comment]
Able to recreate - Digging deeper...

**Comment by Pacific-Alliance-Dev** [comment]
Just as a note, we need to clear the errors at chrome://extensions/ for the extension to work again.

**Comment by Sumedhn97** [comment]
Yes - You have to clear the errors and reload the extension. 
That is the workaround for now..

**Comment by Sumedhn97** [comment]
Here is the issue:
So - when we click the Capture button too many times, the CaptureVisibleTab function in popup.js is invoked beyond the limits that Chrome allows.

My solution would be to:

1)  Disable the Capture button till the CaptureVisibleTab function has been executed
Even with this, there may be a race condition where - the user clicks too many times before it is disabled.

2)  Encapsulate the whole CaptureVisibleTab function with a timeout of 1 second to ensure the delay allows us to remain under the chrome limits.
