### ISSUE TITLE
Need to flush out the screenshots array after generating the PDF report

### ISSUE THREAD

**Issue by Ad-Pav** [Sumedhn97/DragonCapture#2]
Currently, all the images are getting stacked up with every consecutive report.
Need to flush the Screenshot array before proceeding with the new report.

**Comment by Sumedhn97** [comment]
Was able to recreate.
This isn't a bug for the internal teams who use DragonCapture with Selenium automation since every session was to have a collective report for internal streamCollect{} purposes.
But I see that this doesn't make sense for regular human use.

**Comment by Sumedhn97** [comment]
In the next Pull request, I will add a clearScreenshots() function that set screenshots = [] after the "Generate PDF" button is clicked.
